// Logical world coordinates. Pixi views map these to canvas pixels.
// Designed around a 1280x720 reference; resizing handled by the renderer.

export const WORLD = {
  WIDTH: 1280,
  // Tall enough to give the meadow-ground buildings and their contextual
  // upgrade panels room below the hive without the camera clipping.
  HEIGHT: 1000,

  // Vertical bands (meadow at bottom, sky middle, stars top).
  // Horizon was raised when the rock-drop economy added a planting area —
  // foragers haul seeds back to nearest empty meadow tile and need visible
  // grass to plant in.
  MEADOW_Y: 470,
  SKY_Y: 180,
  STARS_Y: 0,

  // Goal flower in the upper sky.
  FLOWER: { x: 640, y: 100, baseRadius: 20 },

  // A massive cracked boulder dominates the RIGHT side of the meadow.
  // Center is the surface-level anchor; the visual draws much bigger than
  // the hive. Cantors fire sparks at it from across the meadow.
  DIG_SITE: { x: 1050, y: 560 },
  // Visual radius of the boulder — bees orbit around it within this radius
  // when picking a strike point.
  DIG_SITE_RADIUS: 120,

  // The single Hive — a honeycomb of hex cells. This is the world-space
  // center of the comb; cells fan outward. The comb is deliberately a
  // small structure in the world — dwarfed by the boulder — so the colony
  // reads as taking on a monumental task. The `hive` camera framing zooms
  // in when it's selected so the cells become workable.
  // Hive sits in the right half of the meadow — closer to the dig-site
  // boulder so the world reads as two halves: a left "economy" strip
  // (pollen silo + wax workshop) and a right "combat" strip (hive +
  // honey jar + the rock the colony is chipping at). Moved ~50% of the
  // distance toward the boulder so the economy buildings have room to
  // grow without overlapping the comb.
  HIVE: { x: 570, y: 545 },
  // Hex cell "size" — the center-to-corner radius. Pointy-top orientation.
  // Small on purpose; see the note on HIVE above.
  HEX_SIZE: 10,

  // Above-ground resource containers:
  //
  //   WAX_BLOCK (left meadow, elevated)                       boulder + drop pile
  //                              ╲                            ╱
  //                               HIVE  ─  HONEY_JAR (above)
  //                              ╱  ╲
  //                    POLLEN_SILO   FERTILIZER_BIN
  //                    (under-hive intake counter, side by side)
  //
  // Foragers spawn-park between the two under-hive intake buildings, then
  // pick the nearest pending task each idle tick: fly LEFT to a meadow
  // flower for pollen, or fly RIGHT to the rock pile to haul a seed (plant
  // it in the meadow) or fertilizer (deliver to the Fertilizer Bin). That
  // centered geometry is what makes the dual-task split feel emergent.
  //
  // The Honey Jar is rendered by HoneyBarView and anchored above the hive
  // (see that file's offsets). Wax Workers pull from the Pollen Silo and
  // deliver to the Wax Block on the left.
  POLLEN_SILO: { x: 490, y: 655 },
  WAX_BLOCK: { x: 290, y: 560 },
  // Fertilizer Bin — composts the rare fertilizer drops from the rock.
  // Sits to the RIGHT of the silo, under the hive, mirroring its silhouette
  // so the two intake buildings read as a pair.
  FERTILIZER_BIN: { x: 650, y: 655 },
  // Honey Jar floats above the hive — its visual is owned by HoneyBarView
  // and bobs ±1px; this is the static reference point for routing logic.
  HONEY_JAR: { x: 570, y: 450 },

  // Overview camera frame — the world-space rect the zoomed-out view fits
  // into. Deliberately shorter (top→bottom) than WORLD.HEIGHT: it stops
  // just below the flower line so the underground band stays hidden until
  // the player zooms in, and the rect is ~16:9 so a typical widescreen
  // canvas fills with minimal letterboxing. Tweaking BOTTOM here is the
  // single knob for "where do the flowers sit on screen in overview."
  OVERVIEW: {
    LEFT: 0,
    RIGHT: 1280,
    TOP: 0,
    BOTTOM: 720,
  },

  // Decorative meadow flowers — clustered on the LEFT half of the meadow
  // away from the boulder. Twelve positions so larger colonies have enough
  // simultaneous work without bees stacking up idle behind claimed flowers.
  MEADOW_FLOWERS: [
    { x: 70, y: 670 },
    { x: 150, y: 695 },
    { x: 240, y: 665 },
    { x: 330, y: 690 },
    { x: 420, y: 670 },
    { x: 500, y: 695 },
    { x: 590, y: 680 },
    { x: 380, y: 700 },
    { x: 270, y: 705 },
    { x: 480, y: 705 },
    { x: 160, y: 670 },
    { x: 60, y: 695 },
  ],
  // Plantable tiles for seed-drops hauled back by foragers. A grid spread
  // across the meadow planting band, avoiding the right (boulder) side
  // and the under-hive intake buildings. Foragers pick the nearest empty
  // tile when planting. Generated by makeMeadowTiles() below.
  MEADOW_TILES: makeMeadowTiles(),
} as const;

function makeMeadowTiles(): { x: number; y: number }[] {
  const out: { x: number; y: number }[] = [];
  // The LEFT meadow is "the field" — overlapping and extending the wild
  // flower patch so planted seeds cluster where the player intuitively
  // looks for flowers. The right side of the meadow is intentionally
  // empty grass; saplings never grow there.
  const rows = [605, 640, 675, 705];
  const cols = [40, 90, 140, 190, 240, 290, 340, 390, 440, 490, 540, 590];
  for (const y of rows) {
    for (const x of cols) {
      // Carve out the under-hive intake buildings (Pollen Silo around
      // x=490, Fertilizer Bin around x=650 — bin is past the right edge
      // of cols, but the silo overlaps).
      const nearSilo = Math.abs(x - 490) < 35 && y > 630 && y < 685;
      if (nearSilo) continue;
      // Jitter so the grid doesn't read as a literal grid — a slight
      // pseudo-random shift on each axis is enough to look natural.
      const jx = ((x * 31 + y * 17) % 11) - 5;
      const jy = ((x * 13 + y * 23) % 9) - 4;
      out.push({ x: x + jx, y: y + jy });
    }
  }
  return out;
}

// Axial hex (q, r) → world pixel position, relative to the hive center.
// Pointy-top layout.
export function hexToWorld(q: number, r: number): { x: number; y: number } {
  const s = WORLD.HEX_SIZE;
  return {
    x: WORLD.HIVE.x + s * Math.sqrt(3) * (q + r / 2),
    y: WORLD.HIVE.y + s * 1.5 * r,
  };
}
